config/routes.rb
Rails.application.routes.draw do
  

  root 'dashboards#index'
  
  devise_for :users
  
  resources :questions do
    resources :quiz_options, only: [:new, :create]
  end
  resources :quiz_options, except: [:new, :create, :index]
  
  resources :quizzes do
    resources :personalities, only: [:new, :create]
    resources :questions, only: [:new, :create, :index]
    collection do 
      get 'results'
    end
  end
  resources :personalities, except: [:new, :create]
  resources :questions, except: [:new, :create, :index]
  resources :user_results, except: [:index]
  
  get '/take_quiz/:id', to: 'user_quizzes#take_quiz', as: 'take_quiz'
  get '/admin', to: 'dashboards#admin', as: 'admin'

end

app/models/question.rb
class Question < ActiveRecord::Base
    belongs_to :quiz
    has_many :quiz_options, dependent: :destroy
    validates :content, presence: true
    validates_uniqueness_of :content, scope: :quiz_id
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_user!
  
  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @quiz = Quiz.find(params[:quiz_id])
    @question = Question.new
  end

  def edit
  end

  def create
    @quiz = Quiz.find(params[:quiz_id])
    @question = @quiz.questions.build(question_params)
      if @question.save
        redirect_to quiz_path(@quiz), notice: 'Question was successfully created.'
      else
        render :new
      end
  end

  def update
      if @question.update(question_params)
        redirect_to quiz_path(@question.quiz.id), notice: 'Question was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @quiz = @question.quiz
    @question.destroy
     redirect_to quiz_path(@quiz), notice: 'Question was successfully destroyed.'
  end

  private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit :class => "success button" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', quiz_path(@question.quiz.id) %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for [@quiz, @question] do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit :class => "success button" %>
  </div>
<% end %>

<%= link_to 'Back', quiz_path(@quiz) %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<strong>Options:</strong>

<table>
  <% @question.quiz_options.each do |opt| %>
    <tr>
      <td><%= opt.content %></td>
      <td><%= opt.points %></td>
      <td>
        <%= link_to 'show', quiz_option_path(opt) %> | 
        <%= link_to 'edit', edit_quiz_option_path(opt) %> | 
        <%= link_to 'delete', opt, method: :delete, data: {confirm: 'are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'add new option', new_question_quiz_option_path(@question) %>
<hr>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', quiz_path(@question.quiz.id) %>