config/routes.rb
Rails.application.routes.draw do
  

  root 'dashboards#index'
  
  devise_for :users
  
  resources :questions do
    resources :quiz_options, only: [:new, :create]
  end
  resources :quiz_options, except: [:new, :create, :index]
  
  resources :quizzes do
    resources :personalities, only: [:new, :create]
    resources :questions, only: [:new, :create, :index]
    collection do 
      get 'results'
    end
  end
  resources :personalities, except: [:new, :create]
  resources :questions, except: [:new, :create, :index]
  resources :user_results, except: [:index]
  
  get '/take_quiz/:id', to: 'user_quizzes#take_quiz', as: 'take_quiz'
  get '/admin', to: 'dashboards#admin', as: 'admin'

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.all
  end

  def results
    @quizzes = Quiz.all
  end

  def show
  end


  def new
    @quiz = Quiz.new
  end


  def edit
  end

  def create
    @quiz = Quiz.new(quiz_params)

      if @quiz.save
       redirect_to @quiz, notice: 'Quiz was successfully created.'
      else
        render :new 
      end
  end

  def update
      if @quiz.update(quiz_params)
        redirect_to @quiz, notice: 'Quiz was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.'
  end

  private

    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def quiz_params
      params.require(:quiz).permit(:name, :description, :image)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= image_tag quiz.image.url(:thumb) %></td>
        <td><%= quiz.name %></td>
        <td><%= quiz.description %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Quiz', new_quiz_path %>
<hr>
<%= link_to 'back to admin', admin_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/results.html.erb
<p id="notice"><%= notice %></p>

<h1>User Results</h1>
<% @quizzes.each do |quiz| %>
<h3><%= quiz.name %></h3>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Points</th>
      <th>result</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% quiz.user_results.each do |user_result| %>
      <tr>
        <td><%= user_result.user.email %></td>
        <td><%= user_result.points %></td>
        <td><%= user_result.personality.description %></td>
        <td><%= link_to 'See details', user_result_path(user_result) %></td>
        <td><%= link_to 'Destroy', user_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<% end %>
<%= link_to 'back to admin', admin_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quiz.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quiz.description %>
</p>
<%= render 'shared/reference_table', quiz: @quiz %>
<strong>image</strong>
<br>
<%= image_tag @quiz.image.url(:medium) %>
<hr>
<p>
  <strong>Personalities (<%= @quiz.personalities.count %>)</strong>
  <table>
    <tr>
    <th>image</th>
    <th>name</th>
    <th>description</th>
    <th>low range</th>
    <th>high range</th>
    </tr>
  <% @quiz.personalities.each do |personality| %>
  <tr>
    <td>
    <% if personality.image_file_name? %>
      <%= image_tag personality.image.url(:thumb) %>
    <% end %>
    </td>
    <td><%= personality.name %></td>
    <td><%= personality.description %></td>
    <td><%= personality.low_range %></td>
    <td><%= personality.high_range %></td>
    <td>
      <%= link_to 'show', personality_path(personality) %> | 
      <%= link_to 'edit', edit_personality_path(personality) %> | 
      <%= link_to 'delete', personality, method: :delete, data: {confirm: 'are you sure?'} %>
    </td>
  </tr>
  <% end %>
  </table>
  <br>
  <%= link_to 'add personality', new_quiz_personality_path(@quiz) %>
  
<hr>

<strong>Questions (<%= @quiz.questions.count%>)</strong>


  <table>
      <% @quiz.questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.quiz_options.count %> options</td>
        <td>
          <%= link_to 'show', question_path(question)%> | 
          <%= link_to 'edit', edit_question_path(question)%> | 
          <%= link_to 'delete', question, method: :delete, data: {confirm: 'are you sure?'} %>
        </td>
      </tr>
      <% end %>
  </table>
  <br>
  
  <%= link_to 'add question', new_quiz_question_path(@quiz) %>

<hr>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>
<hr>
<%= link_to take_quiz_path(@quiz) do %>
  <button class="button">Take this test</button>
<% end %>