config/routes.rb
Rails.application.routes.draw do
  

  root 'dashboards#index'
  
  devise_for :users
  
  resources :questions do
    resources :quiz_options, only: [:new, :create]
  end
  resources :quiz_options, except: [:new, :create, :index]
  
  resources :quizzes do
    resources :personalities, only: [:new, :create]
    resources :questions, only: [:new, :create, :index]
    collection do 
      get 'results'
    end
  end
  resources :personalities, except: [:new, :create]
  resources :questions, except: [:new, :create, :index]
  resources :user_results, except: [:index]
  
  get '/take_quiz/:id', to: 'user_quizzes#take_quiz', as: 'take_quiz'
  get '/admin', to: 'dashboards#admin', as: 'admin'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!, only: [:admin]
  before_action :admin_user!, only: [:admin]

  def index
      @quizzes = Quiz.with_questions_count_greater_than(2)
  end
  
  def admin
  end

end

app/views/dashboards/admin.html.erb
<h1>Admin dashboard</h1>
<hr>
<%= link_to quizzes_path do %>
  <button class="button">Quizzes</button>
<% end %>
<%= link_to results_quizzes_path do %>
  <button class="button">Results</button>
<% end %>

app/views/dashboards/index.html.erb
<h1>Personality Quizzes</h1>

<p>Take one of our quizzes!!</p>

<% @quizzes.all.each do |quiz| %>
  <h3><%= quiz.name %></h3>
  <%= link_to take_quiz_path(quiz) do %>
    <%= image_tag quiz.image.url(:medium) %>
  <% end %>
  <p><%= quiz.description%></p>
  <%= link_to take_quiz_path(quiz) do %>
    <button class="button">Take this Quiz</button>
  <% end %>
  <hr>
<% end %>